name: 01-workflow
on: 
    workflow_dispatch:

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo Hello World
    second-job:
        runs-on: ubuntu-latest
        steps:
            - name: Say Good bye
              run:  echo Good Bye
            - name: Failed step
              run: |
                echo Hi How are you?
                exit 0
            
            - name: list directory
              run: ls 