name: 01-workflow
on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo Hello World
    second-job:
        runs-on: ubuntu-latest
        steps:
            - name: Say Good bye
              run:  echo Good Bye
            
            - name: list directory
              run: ls 