name: 02 - workflow events
on: push

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: echoing event
              run: Workflow triggered by ${{github.event_name}} event