name: 02 - workflow events
run-name: Run By ${{github.actor}}

on: 
    push: 
    pull_request:
    workflow_dispatch:

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: echoing event
              run: echo Workflow triggered by ${{github.event_name}} event
